### ISSUE TITLE
New branch

### ISSUE THREAD

**Issue by DaniMorales97** [Priyansh61/Space-Fighters#2]
Hi

I made a new branch in my fork repo called sprites. I did it that way to maintain the original approach you had, because I did massive changes in that new branch. I remade your game but with a different approach, sprites. I don't know if you know about them or how to work with them but I wanted to recommend that you take a look into my approach. I think it's more readable and easier to maintain.

Next I'm going to add score and highscore. Also I thought about introducing new types of enemies, you can see that in enemy.py and maybe give them a health system or something. 

I think you can create a new branch and merge mine. That way you can keep your original branch in case you want to continue working with that approach. Feel free to make some changes and show them to me or suggest any ideas for more things we can implement.

**Comment by Priyansh61** [comment]
Hello @DaniMorales97 
Your comment has made me more curious  to look into the awesome changes you have made in the project and i am really looking forward to take a look at those changes.

I would be glad if you can make a PR so that i can create a new branch and merge it and both of us can collaborate on that.

It's really fun working with you on this project and i hope with your efforts we will be able to make the game much more enjoyable and learner friendly.

Really excited to see the PR.

**Comment by DaniMorales97** [comment]
Oh, okay. I'll do it right away. I'm new to github and I thought that as it was your repo that I forked that you would be able to merge automatically without need of me doing a PR.
