### ISSUE TITLE
Game crashes due to empty laser list

### ISSUE THREAD

**Issue by Priyansh61** [Priyansh61/Space-Fighters#3]
`File "/home/priyansh/Python2/projects/space-invaders/main.py", line 268, in <module>
    menu()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 260, in menu
    main()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 248, in main
    redraw_window ()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 201, in redraw_window
    menu()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 260, in menu
    main()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 239, in main
    player.move_laser(enemies,4)
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 106, in move_laser
    self.lasers.remove(laser)
ValueError: list.remove(x): x not in list`
<section>
  <h3>Error Generation:</h3>
  <p>The error is generated whenever you continuosly press the space bar to shoot the lasers.</p>
</section>
<section>
  <h3>Attempted Fixes :</h3>
  <p>Tried making if else statement so that the laser is not removed from the list when the size of the list is less than a particular size but this doesn't fix the issue.</p>
</section>

**Comment by DaniMorales97** [comment]
I tried to force this bug to happen using your original code and I don't think it happens because you press continuously the space bar to shoot, because I wasn't able to get the error a lot of times and I was always pressing the space bar. I also think it doesn't have anything to do with if the list is empty or not.

Checking the error message and analysing the code to see why it would happen I have the theory that it happens when a laser hits more than one enemy at the same time, so in the for loop it gets removed once per enemy, but you can only remove it once, so the second time it gives the error. I'm not totally sure though.

However, the solution is simple and you don't have to worry about finding out what exactly is making the error happen, unless you want to find out for learning purposes. The only thing you have to add is an if statement that checks if that element exists in that list before removing it:
```
def move_laser(self,objs,vel) :  
        for laser in self.lasers:
            laser.move(vel)
            if laser.off_screen(HEIGHT) :
                self.lasers.remove(laser)
            else:
                for obj in objs :
                    if (laser.collision(obj)) :
                        objs.remove(obj)
                            if laser in self.lasers:
                                self.lasers.remove(laser)
```
I'll add a commit to my main branch and make a PR. It also has other commit fixing typos etc.
