### ISSUE TITLE
error in loading images from the path

### ISSUE THREAD

**Issue by Priyansh61** [Priyansh61/Space-Fighters#8]
<h3>Genenrated Error</h3>

`Traceback (most recent call last):
  File "/home/priyansh/Python2/projects/space-invaders/code/main.py", line 49, in <module>
    MENU = pygame.image.load(MENU_path)
FileNotFoundError: No such file or directory: '/home/priyansh/Python2/projects/space-invaders/code/././assets/menu.png`

<h3>Errror Fix:</h3>

Use this 

`directory = os.path.dirname(os.path.abspath(__file__)) MENU_path = os.path.join( directory, "../assets/menu.png") `

instead of

`MENU_path = os.path.join( os.path.abspath(__file__)), "../assets/menu.png")`

<h3>Question</h3>
<ul>
  <li>is this happening on my system only ?? </li>
  <li>Why is the error generateid?? </li>
</ul>

**Comment by DaniMorales97** [comment]
I don't know why your line of code is:
```
MENU_path = os.path.join( os.path.abspath(__file__)), "../assets/menu.png")
```

Right now I have an updated version, but checking that version it should be:
```
MENU_path = os.path.join(os.path.abspath(__file__), "../../assets/menu.png")
MENU = pygame.image.load(MENU_path)
```

Notice how that line works:
It is joining the path to the module that is running to whatever string you put inside "", adding a /. So it is not working with your line of code because the path that ``os.path.join()`` is returning is, as you can see in your error message:
``
 /home/priyansh/Python2/projects/space-invaders/code/././assets/menu.png
``
Which is inside the ``/code`` directory, because you are missing "../" in your string, notice that ".." means go to upper directory.

So the line:
```
MENU_path = os.path.join(os.path.abspath(__file__), "../../assets/menu.png")
```
Works this way: **Edit: I was wrong here, check the rest of the comments in this issue**
The first "../" gets from ``/main.py`` to ``/code``, that contains it, and the second gets to the directory that contains the ``/code`` directory. Afterwards, the rest of the path gets inside the ``/assets`` directory, and looks for a "menu.png" file.

Your solution is correct, but adds a line of code and, even though you could put it all inside only one line, it would be a large one. However, the only thing different that accomplishes using ```os.path.dirname()``` is that you get the directory that contains the file that you pass through it. So it would be easier to just use one "../" more.

**Comment by Priyansh61** [comment]
hey @DaniMorales97 

I dont know while tweaking with the code i might have missed the 
`../../assets`

But when i cloned your files again and tried it back i am still getting the same error message

`File "/home/pm/Projects/Space-Fighters/code/main.py", line 49, in <module>
    MENU = pygame.image.load(MENU_path)
FileNotFoundError: No such file or directory: '/home/pm/Projects/Space-Fighters/code/main.py/../../assets/menu.png'.`

Due to this i have to add one more line of code and specify the directory as mentioned above , so could you please help me figure out where i am going wrong ??

**Comment by DaniMorales97** [comment]
I don't know what is wrong now.

We can see it together in a discord call sharing your screen.

**Comment by DaniMorales97** [comment]
Is it possible that you are using an old version of python? I've investigated a bit to see if I find why you get that issue and that might be the answer. However, I also noticed that writting ``os.path.dirname(os.path.abspath(__file__))`` should be, in my understanding, the same as ``os.path.dirname(__file__)`` which es shorter and clearer. Try it please.

**Comment by DaniMorales97** [comment]
This issue should be closed now. We understand now that `/..` does not work to go up from the path of a _file_, as I initially thought, it is meant to go up from the path of a _directory_. It was working in my pc, with Windows OS and it wasn't for @Priyansh61 that uses Linux. From now on the syntax used will be `os.path.dirname(__file__)` plus the path to the file being imported starting from the directory containing the file that is importing it. PR #9 applies this syntax change.

**Comment by Priyansh61** [comment]
Thanks for your efforts @DaniMorales97 .
